### ISSUE TITLE
run software locally?

### ISSUE THREAD

**Issue by 886419** [ACI-Rental/backend#45]
Is it possible to run (some of the) software locally on my machine? Local DB, local browser, preferably without Docker.

* which services are required (usecase dependent?) With/without API gateway?
* prerequisites: data (users, products?), environment variables?

I followed 'Overdrachtsdocument.pdf' upto 'SQL Server Management Studio'. All unittests pass. 
Perhaps only a proper setting of 'aci_db_string' is needed per project in the solution to start with IIS Express?

**Comment by SieBRUM** [comment]
Everything is locally runnable without docker. just set the env-variable to the correct database-string and it will use these settings. If you'd like to just use one database (so not 1 database per service), make sure to not include the 'DATABASE_NAME' string inside the env-variable.  

The required services are dependent of the services you'd like to edit/run. So you are able to run the product service, without the ImageService. Please note that calls that requir the imageservice to run, will fail.

All services are able to run without the apigateway LOCALLY. We suggest not exposing these services in a production environment and only exposing the ApiGateWay (and let the gateway re-route data to local instances of services in ex. kubernetes). 

Most pre-requisites can be found in the 'docs' in the 'CONTRIBUTING.md' file. https://github.com/ACI-Rental/docs/blob/main/CONTRIBUTING.md#started

**Comment by 886419** [comment]
ah yes, it's even mentioned on the frontpage. I'll rtfm better next time, thx!
