### ISSUE TITLE
Upgrade microservices naar .NET 6

### ISSUE THREAD

**Issue by Marc-2000** [ACI-Rental/backend#50]

**Comment by 886419** [comment]
Impact analysis?
- How risky is this to do 'all-at-once'? Do we need E2E test first?
- If service migration sequentially over several sprints (eg when service impacted by a userstory), can the total application still be run outside docker on a dev PC (where only 1 .NET version is available).
- Is .NET6 backward compatible (and EntityFramework?)

**Comment by Marc-2000** [comment]
- E2E testing shouldn't make a difference because nothing changes about the logic of the application. Only packages will be updated. It is not super risky because it is quit easy to upgrade to .NET 6 + we can always revert this per service if problems would occur. 
- We should make clear which version of .NET should be downloaded if a dev only has one version of .NET. For each version there are SDK's available.
- Yes (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility#:~:text=NET%20Framework%204.5%20and%20later,work%20without%20modification%20on%20the%20.)
