### ISSUE TITLE
Refactor MicroServices

### ISSUE THREAD

**Issue by Noodleyy** [ACI-Rental/backend#51]
- NoteService can be part of ProductService as NoteServices is dependant on ProductService. 

- UserService will be redundant as soon as Auth0 gets implemented.

- ImageService should no longer save images as a bytearray into the SQL database. Instead a blobstorage shall be used to store images.

**Comment by 886419** [comment]
> NoteServices is dependant on ProductService
Are you sure the NoteServices does not need a separate lifecycle/scalability etc?
What's the longterm purpose of the Noteservice exactly? Any other reason to merge them than just a dependency?
