### ISSUE TITLE
Add Sonar Analyzer to CI/CD pipeline

### ISSUE THREAD

**Issue by rachied** [ACI-Rental/backend#57]
Using Sonar, we can analyze our source code for known security mishaps and other commonly made mistakes. If configured right, it can also tell us about (unit/e2e) test coverages.

This can be done with SonarCloud (which might cost money), or using a self hosted SonarQube instance. 

Research and implement which option is best, and find out if there are integrations possible with Github (such as automatically posting Sonar results on a PR).

**Comment by 886419** [comment]
i'd rather it breaks the build.
